version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KV!X(;=JA4B[C8y%F]kM7m
      MYSQL_DATABASE: patients
      MYSQL_USER: admin
      MYSQL_PASSWORD: p_,7*AxH;YP)FnRwD2Cuhk
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
